### ISSUE TITLE
script stops with "/Library/LaunchDaemons/: No such file or directory"

### ISSUE THREAD

**Issue by vrl2** [freayd/clamav-tools#1]
Thanks for creating this script! When I attempt to run it, it stops with the following errors:
`./install-on-macos.sh 
tee: /Library/LaunchDaemons/clamav.clamd.plist: No such file or directory
tee: /Library/LaunchDaemons/clamav.freshclam.plist: No such file or directory
chown: /Library/LaunchDaemons/clamav.clamd.plist: No such file or directory
chown: /Library/LaunchDaemons/clamav.freshclam.plist: No such file or directory
chmod: /Library/LaunchDaemons/clamav.clamd.plist: No such file or directory
chmod: /Library/LaunchDaemons/clamav.freshclam.plist: No such file or directory
/Library/LaunchDaemons/clamav.freshclam.plist: No such file or directory
/Library/LaunchDaemons/clamav.clamd.plist: No such file or directory`
I'd appreciate any suggestions to work around this! Thanks.

**Comment by freayd** [comment]
Hi. Thanks for reporting the issue. It seems that, somehow, the tee command failed to create the plist files. Could you please run these commands in a terminal and paste the output here? Thanks

```
sudo ls -ld /Library/ /Library/LaunchDaemons /Library/LaunchDaemons/clamav.clamd.plist
sudo tee /Library/LaunchDaemons/clamav.clamd.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>clamav.clamd</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/sbin/clamd</string>
        <string>--foreground</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/clamd.error.log</string>
</dict>
</plist>
EOF
```

**Comment by vrl2** [comment]
`
$ sudo ls -ld /Library/ /Library/LaunchDaemons /Library/LaunchDaemons/clamav.clamd.plist
ls: /Library/LaunchDaemons: No such file or directory
ls: /Library/LaunchDaemons/clamav.clamd.plist: No such file or directory
drwxr-xr-x+ 60 root  wheel  2040 Jan  1 16:26 /Library/
`
`
$ sudo tee /Library/LaunchDaemons/clamav.clamd.plist
tee: /Library/LaunchDaemons/clamav.clamd.plist: No such file or directory
`
The last command causes Terminal to hang up.
> sudo ls -ld /Library/ /Library/LaunchDaemons /Library/LaunchDaemons/clamav.clamd.plist
> sudo tee /Library/LaunchDaemons/clamav.clamd.plist

**Comment by freayd** [comment]
The LaunchDaemons folder is somehow missing on your computer. The commit 7ee5ccfcdc12cb39cde4ba4814473c15e8a9a09d should automatically create it. Can you get the latest version of the script and try again?

**Comment by vrl2** [comment]
Great! Thank you - no longer stops with the previous error. The commands
"freshclam" and "clamscan" work normally.

**Comment by freayd** [comment]
I'm glad the fix worked. Thanks for opening the issue.
